---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.include: |
    log
  htdom.server: |
    htdom.local.:53 {
      forward . 192.168.xxx.xxx
    }
