---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
type: Opaque
data:
  db_hostname: bWFyaWFkYi5odGRvbS5sb2NhbA==
  db_username: bmV4dGNsb3Vk
  db_password: dmFuMUdvY2gjIw==
  db_name: bmV4dGNsb3Vk
