---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
type: Opaque
data:
  nextcloud_admin_user: bmV4dGNsb3VkLWFkbWlu
  nextcloud_admin_password: dmFuMUdvY2gjIw==