---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - server-certificate.yaml
  - ingress.yaml
  - persistent-volume-claim.yaml
